### ISSUE TITLE
Redump: "null"s and "undefined"s appearing in ringcode

### ISSUE THREAD

**Issue by JohnVeness** [nightson/UserScripts#6]
Given the following (partial) JSON:
```
    "d_ring_0_ma1": "sonopress arvato 52064832/EAE07705224D CC 22",
    "d_ring_0_ma1_sid": "IFPI LB 50",
    "d_ring_0_ts1": "",
    "d_ring_0_mo1_sid": "IFPI 07G6",
    "dr_ring_0_mo1": "",
    "d_ring_0_ma2": null,
    "d_ring_0_mo2_sid": "IFPI 07D7",
    "d_ring_0_ma3": null,
    "d_ring_0_ma4": null,
    "d_ring_0_offsets": "1",
    "d_ring_count": "1",
```
I get the following in the newdisc ringcode textbox:
```
Data Side:
Mastering Ring: sonopress arvato 52064832/EAE07705224D CC 22
Mastering SID: IFPI LB 50
Toolstamp/Mastering Code: 
Mould SID: IFPI 07G6
Additional Mould: 

Label Side: 
Mastering Ring: null
Mastering SID: undefined
Toolstamp/Mastering Code: undefined
Mould SID: IFPI 07D7
Additional Mould: undefined
```
I'd expect there to be no text where there are currently `null`s and `undefined`s.

**Comment by nightson** [comment]
For `null `s, I don't really understand why null and empty string are both being used for entries with no value. I think the older versions of MPF only use empty string.

For `undefined`s, are you using a legit JSON file output by MPF? If there is d_ring_0_ma2, there should be d_ring_0_ma2_sid as well, unless MPF has changed the way it outputs JSON. In that case, I may need to to rewrite the whole ring code text generation part.

**Comment by JohnVeness** [comment]
Yes, this is genuine output from MPF 2.3. I have a small collection of jsons, from PC DVD-ROM-5s and DVD-ROM-9s if you want them. I did consider this could be a bug in MPF but to be honest every time I look at the code, with all the similarly-named fields, my eyes go cross-eyed.

**Comment by nightson** [comment]
https://github.com/nightson/UserScripts/commit/716155bf606a44d8dda290a8d3291046bf178871

Could you test if the fix works correctly before I bump the version number? It works fine here with minimal testing. I mainly dump PC CD games and don't have a lot of JSON files for different platform at hand.

**Comment by JohnVeness** [comment]
Thanks, I have tested this (after commenting out the call to resetForm() for now!, see #5), and it seems to work fine with all my PC DVD-5s and DVD-9s. I haven't tested it with any other formats yet, but I will keep an eye on the ringcode output before submitting any forms, and let you know if I see any oddities.

**Comment by nightson** [comment]
I don't have any issue with `resetForm()` here. It's really weird. Could you check the browser console to see if there is any error warning?

Just moved the placeholder replacing part to the parse function and bumped the version number.

https://github.com/nightson/UserScripts/commit/2798dbff0ccb13f8c752c5ad7d384c124e08dc3e
