### ISSUE TITLE
Integrate Redump Disc Page userscript?

### ISSUE THREAD

**Issue by mariomadproductions** [nightson/UserScripts#7]
[redump-disc-page.txt](https://github.com/nightson/UserScripts/files/8909273/redump-disc-page.txt)
Might be a good idea to integrate this script - it displays the datfile name on the disc page.

**Comment by nightson** [comment]
Hmm, that script does quite different things than mine and works on different web pages too. It's probably better to keep them separate. 

Thanks for the suggestion!

**Comment by mariomadproductions** [comment]
Yeah that's reasonable. They seem to work fine side-by-side anyway.
